# Generated by Django 3.2.21 on 2023-09-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_description_recipe_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
