# Generated by Django 3.2.21 on 2023-09-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
