# Generated by Django 4.2.5 on 2023-09-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_recipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='uuid.uuid1', max_length=200, unique=True),
        ),
    ]
